### ISSUE TITLE
rending pdf error

### ISSUE THREAD

**Issue by andrewpbray** [stat20/course-materials#439]
Hi @ryanlovett ,

I'm encountering an error and spent about 45 min trying to put together a MRE to put on a Quarto forum but have been unsuccessful, so I figured I'd ping you to see if you have any insight, since you can make more sense of the Maximal Reproducible Example that is the Stat 20 repo.

At issue is the GHA called [Publish Live Website to stat20.org](https://github.com/stat20/stat20/actions/workflows/publish-live-site.yml). This action will eventually be set to trigger as a CRON job to only render the materials (notes, assignments) up through the time of publishing. As part of #409 , I've added a new script, [`prep-next-readings.r`](https://github.com/stat20/stat20/blob/main/assets/scripts/prep-next-readings.r) that posts pdfs for the week on the homepage (before they're rendered as htmls and join the rest of the Notes section).

The workflow doesn't error out completely, but the `prep-next-readings.r` script does error out. You can find the error here:

 <https://github.com/stat20/stat20/actions/runs/5514907451/jobs/10054685109#step:4:147>
 
I was able to recreate the bug in a local container if I run `r assets/scripts/prep-next-readings.r` at the terminal. However, when I source the script from within RStudio, it runs just fine.

The closest explanation I've found online is that "you would need to have Quarto in PATH which you won't have if you only use the RStudio bundled version." That comes from cderv's comment here:  <https://github.com/quarto-dev/quarto-cli/issues/2380>.

My semi informed guess is that when sourcing the script within RStudio, the `quarto::quarto_render()` function is calling `quarto render` using the installation of Quarto that comes with the IDE. When running the script from the terminal, it's not finding Quarto on the path.

What do you make of this? If you're too busy or don't want to dive down a debug rabbit hole, no prob, just let me know and I'll post it to either github or rstudio community.

**Comment by andrewpbray** [comment]
@ryanlovett Interestingly, I haven't been able to recreate it in a Minimal Working Example. Here is that successful GitHub Action:

<https://github.com/andrewpbray/mwe/actions/runs/5525430622/jobs/10079033225>

All this does is pull `rocker/verse` and sources an r script that runs `quarto::quarto_render()` to a pdf. Is the problem that in the `stat20/stat20-docker` image we are also manually installing Quarto? That's in the Dockerfile here:

<https://github.com/stat20/stat20-docker/blob/b1f5d9247567430db75ac0c28179d2f3617c267b/Dockerfile#L33>

**Comment by ryanlovett** [comment]
@andrewpbray Sorry, I initially missed this issue's mentions. I'll take a look at this tonight or tomorrow.

**Comment by ryanlovett** [comment]
When rocker [installs quarto](https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_quarto.sh) it is made available through the embedded RStudio version at /usr/lib/rstudio-server/bin/quarto/bin/quarto. rocker symlinks to it in /usr/local/bin. That path is referenced in /etc/profile so that bash shells prepend it onto PATH.

The quarto package we install (due to an issue with the older version in rocker) puts it into /opt/quarto/bin/quarto, and updates the /usr/local/bin symlink. So either way /usr/local/bin/quarto is in PATH for any shell that sources /etc/profile. The github action specifies `shell: bash` so I would expect quarto to be found. `quarto::quarto_render` invokes [`find_quarto`](https://github.com/quarto-dev/quarto-r/blob/main/R/render.R#L78) which [first looks at](https://github.com/quarto-dev/quarto-r/blob/main/R/quarto.R#L19) `QUARTO_PATH` and then looks for it in PATH.

So as a workaround, we could set `ENV QUARTO_PATH=/usr/local/bin/quarto` in the Dockerfile so that no searching is necessary, though I'm not sure why that should be necessary. The variable could instead be set in the workflow environment so that it only is done during CI, e.g. in the [env section](https://github.com/stat20/stat20/blob/main/.github/workflows/publish-live-site.yml#L17) or in just the invocation that needs it, `env QUARTO_PATH=/usr/local/bin/quarto r ./assets/scripts/prep-next-readings.r`.

For debugging, without setting QUARTO_PATH, you could also insert something like `echo PATH=$PATH` right before that command so that if/when it does fail, we know if the action is somehow causing this.

**Comment by andrewpbray** [comment]
@ryanlovett 

Ah, good suggestions. I've added that debug echo line and also tried passing the `QUARTO_PATH` variable:

https://github.com/stat20/stat20/blob/78980eb78b05a3ab04c2414fb94066c7fed18756/.github/workflows/publish-live-site.yml#L34-L38

However the GitHub actions still is erroring out when running that script:

<https://github.com/stat20/stat20/actions/runs/5590051376/jobs/10219247985>

Any ideas?

**Comment by ryanlovett** [comment]
@andrewpbray Hmm, could you please create a branch I can modify and trigger workflows from?

**Comment by andrewpbray** [comment]
You should be able to push here:

<https://github.com/stat20/stat20/tree/debug-pdf-preview>

And watch the builds here: <https://github.com/stat20/stat20/pull/442>

Does that work?

**Comment by ryanlovett** [comment]
I should have looked at the exact error more closely. It is not failing because it could not find `quarto` -- it was found and was executed, but it errored out.

https://github.com/stat20/stat20/actions/runs/5626028119/job/15246004041#step:4:153

So the problem is even more mysterious if it can't be reproduced in a local image. I'm still looking...

**Comment by ryanlovett** [comment]
I inserted a wrapper around quarto, renaming the real quarto to be /usr/local/bin/quarto.real and then creating a /usr/local/bin/quarto script that captured the options quarto was being invoked with. quarto wrapper:

```
#!/bin/bash

# capture cli arts
echo "$@" > /tmp/quarto.$$

# run the real quarto
exec /usr/local/bin/quarto.real $@
```

It is being called as
```bash
quarto render 2-summarizing-data/09-summarizing-associations/notes.qmd --to pdf
```

When I manually ran that from a terminal, it succeeded. So somehow the quarto library is having trouble running the quarto executable.

The error is being raised from https://github.com/quarto-dev/quarto-cli/blob/907d4c265173d22362e510866b67f724c5150c96/src/resources/rmd/patch.R#L25.

**Comment by ryanlovett** [comment]
If the render calls within `assets/scripts/prep-next-readings.r` are moved outside of the script, to the calling github workflow, then it succeeds.

More importantly, running the script as-is with Rscript rather than littler also works! I don't know enough about littler to understand why the script doesn't run the same way as it does in RStudio or Rscript. Switching to Rscript seems like an easy win. I'll leave the other `r` invocations as-is though they could probably be changed too.
